<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('members')->insert([
            [
                'nama' => 'Nurmila',
                'npm' => '2020020106',
                'angkatan' => 'VII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Juliani',
                'npm' => '2020020111',
                'angkatan' => 'VII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Rafita Manda',
                'npm' => '2022020111',
                'angkatan' => 'IX',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Amirul Mukmin',
                'npm' => '2021020111',
                'angkatan' => 'IX',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Fitrah Ramadhan',
                'npm' => '2021020111',
                'angkatan' => 'IX',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Darmawan Setiawan',
                'npm' => '2020020111',
                'angkatan' => 'VII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Ricky Mahendra',
                'npm' => '2019020111',
                'angkatan' => 'VI',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Abdul Rahman',
                'npm' => '2019020111',
                'angkatan' => 'VI',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'A. Akbar',
                'npm' => '2020020111',
                'angkatan' => 'VII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Arham Irfa',
                'npm' => '2022020092',
                'angkatan' => 'IX',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Muh Shafar Ifratama',
                'npm' => '2020020092',
                'angkatan' => 'VII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Sri Wahyuni',
                'npm' => '2020010009',
                'angkatan' => 'VIII',
                'jurusan' => 'Manajemen Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Nursanti',
                'npm' => '2020010014',
                'angkatan' => 'VIII',
                'jurusan' => 'Manajemen Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => "Mudzakkir Ma'arif AM",
                'npm' => '2020020003',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Andi Khozin Mubarak',
                'npm' => '2020020007',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Wahyu Pratama',
                'npm' => '2020020061',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Rio Saputra JF',
                'npm' => '2020020076',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Anggi Prayoga',
                'npm' => '2020020082',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Bau Annisa Fitri',
                'npm' => '2020020085',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Andy Firwansyah',
                'npm' => '2020020086',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Muh Rafli Fahreza',
                'npm' => '2020020088',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Andi Cinta Ika Wahyuni',
                'npm' => '2020020093',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Firman Satria',
                'npm' => '2020020101',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Andi Meisya',
                'npm' => '2020020118',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Andi Nur Azizah',
                'npm' => '2020020119',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Putriani Jamal',
                'npm' => '2020020128',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Diwa Febrian',
                'npm' => '2020020131',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Ari Wibowo',
                'npm' => '2020020132',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'M. Adhim Wardhana',
                'npm' => '2020020133',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Nur Nabila',
                'npm' => '2020020154',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Ihsan Dwianto',
                'npm' => '2020040001',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Informasi',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Sukmawati',
                'npm' => '2021010011',
                'angkatan' => 'VIII',
                'jurusan' => 'Manajemen Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Muh Adnan',
                'npm' => '2021020002',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Yunita',
                'npm' => '2021020005',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Alviana Vinandia Manongkan',
                'npm' => '2021020006',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'M. Yusuf',
                'npm' => '2021020014',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Aisyah Sarah Salwa',
                'npm' => '2021020017',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Fransisla L Anom',
                'npm' => '2021020024',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Putri Aprilya Utami',
                'npm' => '2021020026',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Dewi Lukas',
                'npm' => '2021020027',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Citra Irawati',
                'npm' => '2021020031',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Hasyim Syahid Salihun',
                'npm' => '2021020046',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Muhammad Junaid',
                'npm' => '2021020064',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Galang',
                'npm' => '2021020065',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Irsyandi Syam',
                'npm' => '2021020079',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Junita Frastinera',
                'npm' => '2021020085',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Ahmad Rifai',
                'npm' => '2021020103',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Abd Mugni',
                'npm' => '2021020111',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Muslimah Safitri',
                'npm' => '2021020157',
                'angkatan' => 'VIII',
                'jurusan' => 'Teknik Informatika',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Sadriadman',
                'npm' => '2021030007',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Reksan',
                'npm' => '2021030008',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Mateos Lengmani',
                'npm' => '2021030011',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Irfan Salim Hidayat',
                'npm' => '2021030015',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Desi Ratnasari',
                'npm' => '2021030016',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
            [
                'nama' => 'Nova Lastriani',
                'npm' => '2021030017',
                'angkatan' => 'VIII',
                'jurusan' => 'Sistem Komputer',
                'gambar' => 'ari.jpg',
            ],
        ]);
    }
}
